name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install ruff
      - run: ruff check --output-format=github .

  test:
    name: Run tests

    strategy:
      matrix:
        python-version: ['3.8', '3.x']
        operating-system:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -e '.[test]'
      - name: Run test suite
        run: |
          pytest --cov parametrize_from_file
          docs/test_docs.sh
      - name: Report test coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          coveralls
